### ISSUE TITLE
code码有很多重复

### ISSUE THREAD

**Issue by ljlin0903** [nhjclxc/District-SQL#1]
我是直接下载的梳理好的sql，里面有很多重复的code

**Comment by nhjclxc** [comment]
> 我是直接下载的梳理好的sql，里面有很多重复的code

我的数据都是从高德来的，数据是肯定没有错的。
至于code重复是会有的，乡镇级别的数据没有具体的code，用的是父级的code，code最小一级是到县区级别。
还有就是city_code只到地区市的级别，所以市下面的所有区县乡镇都是和对应的市一样的

**Comment by ljlin0903** [comment]
明白了，谢谢老哥的分享，对我很有帮助！
